version: '3.9'

services:
  dev-minio:
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'

  dev-postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=crossword-solver_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=5432
    volumes:
      - "crossword-solver-postgres-data:/var/lib/postgresql/data"

volumes:
  minio_data:
    driver: local
  crossword-solver-postgres-data:
